apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-api
  name: demo-api
  namespace: demo-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: demo-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - image: us.gcr.io/kubernetes-demo-gdsc/demo-api:v1.0
          imagePullPolicy: IfNotPresent
          name: demo-api
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "275m"
              memory: "275Mi"
            limits:
              cpu: "750m"
              memory: "1500Mi"
          env:
            - name: PORT
              value: "5000"
            - name: GCP_PROJECT_ID
              value: kubernetes-demo-gdsc
            - name: GOOGLE_FIRESTORE_SA
              value: /secrets/firestore_sa.json
            - name: API_ENV
              value: PROD
            - name: DEBUG_MODE
              value: "false"
          volumeMounts:
            - mountPath: /secrets/
              name: firestore-sa-credentials
              readOnly: true
      volumes:
        - name: firestore-sa-credentials
          secret:
            secretName: firestore-sa-credentials
      imagePullSecrets:
        - name: gcr-secret
