apiVersion: v1
kind: Service
metadata:
  name: demo-api-lb
  labels:
    app: demo-api
  namespace: demo-namespace
spec:
  selector:
    app: demo-api
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
