apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
  labels:
    app: demo-api
  namespace: demo-namespace
spec:
  selector:
    app: demo-api
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
