apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-web
  name: demo-web
  namespace: demo-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: demo-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
        - env:
            - name: REACT_APP_API_BASE_URL
              value: /api/
            - name: NODE_ENV
              value: production
          image: us.gcr.io/kubernetes-demo-gdsc/demo-web:v1.0
          imagePullPolicy: IfNotPresent
          name: web-demo
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gcr-secret
