apiVersion: v1
kind: Service
metadata:
  name: demo-web-service
  labels:
    app: demo-web
  namespace: demo-namespace
spec:
  selector:
    app: demo-web
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
